/*
I SOLVED THE PROBLEM WITH MY OWN SOLUTION BEFORE LOOKING AT THIS ALGORITHM (also i understand this now)
NO I"M NOT TRANSLATING MY ORIGINAL CANCEROUS 100 LINE PYTHON SOLUTION SO THAT IT DOESN'T MLE
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT I"M NOT
GO READ THE CANCER SUB FUCK YOU I"M NOT TRANSLATING IT
https://dmoj.ca/src/2174078
^^^^ PURE CANCER STAGE 4 djfl;ajd;lfJDLFJLDjfdasjfl;kjasd;lfj;lsjdJF
*/
#include <bits/stdc++.h>
using namespace std;
int d, num, N;
int dp[50001];
int dist[50001];
vector<vector<int>>graph(50001);
void dfs(int node, int p){
    dist[node] = 0;
    dp[node] = 1;
    for (int n: graph[node]){
        if (n == p) continue;
        dfs(n, node);
        if (dist[node]+dist[n]+1>d){
            d = dist[node]+dist[n]+1;
            num = dp[node]*dp[n];
        }
        else if (dist[node]+dist[n]+1==d){
            num += dp[node]*dp[n];
        }
        if (dist[n]+1>dist[node]){
            dist[node]=dist[n]+1;
            dp[node]=dp[n];
        }
        else if(dist[n]+1==dist[node]){
            dp[node]+=dp[n];
        }
    }
}
int main(){
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    cin >> N;
    for (int i = 0; i<N-1; i++){
        int a,b;
        cin >> a >> b;
        graph[a].push_back(b);
        graph[b].push_back(a);
    }
    dfs(1, -1);
    cout << num;
}